# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eb57f6532db3c33fffc8f3d83c9a1a621178a012af0d57fcf111867dcf26c9d3402a88049a0e9a80dd92e6e297b72f6528e263d78a36ed8b79fc0412ba50a3e

test:
  secret_key_base: 01a8ad877ca84139cd43db8b2b73e384381e2eb4cb36d7c1a048b3ac64f4aabb13e013f21aeaff060afa37972d1a02ed406d2bcba3c76d3c60970ba1ad5ebf14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
